# Generated by Django 5.1.2 on 2024-12-08 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_part_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='image',
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='part_images/')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.part')),
            ],
        ),
    ]
