# Generated by Django 5.1.2 on 2024-12-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_part_image_partimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='condition',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='engine_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Engine capacity in cc', null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='engine_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
