# Generated by Django 5.1.2 on 2024-12-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_part_condition_part_engine_capacity_part_engine_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='part',
            name='description',
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
